# Generated by Django 4.2 on 2023-05-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
    ]
